version: '3'
services:
  mysqldb:
    image: mysql:8.0.32
    container_name: mysqldb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: devopsback
    networks:
      - mon_reseau
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mysqldb
    networks:
      - mon_reseau
    ports:
      - "8083:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/devopsback
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - mon_reseau
    depends_on:
      - springboot-app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - mon_reseau
    depends_on:
      - prometheus
    volumes:  # Créez un volume pour Grafana
      - grafana_data:/var/lib/grafana

  front-end:
    image: karma12/front:v1
    container_name: front-end
    ports:
      - "80:80"
    networks:
      - mon_reseau

networks:
  mon_reseau:
    driver: bridge

volumes:
  mysql_data:
  grafana_data:  # Créez un volume pour Grafana
