global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator-distant'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.1.181:8083']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['192.168.1.181:8080']

