apiVersion: v1
kind: Service
metadata:
  name: dev-backend
  labels:
    name: backend-service
spec:
  type: NodePort
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30008
  selector:
    app: backend-app
