apiVersion: v1
kind: Service
metadata:
  name: springboot-backend2    # Nom unique pour votre nouveau service Spring Boot
  labels:
    name: backend-service2     # Étiquette unique pour votre nouveau service Spring Boot
spec:
  type: NodePort
  ports:
    - port: 8030
      targetPort: 8030
      nodePort: 30008
  selector:
    app: backend-app2          # Étiquette unique pour votre nouveau déploiement Spring Boot