apiVersion: v1
kind: Service
metadata:
  name: springboot-backend3   # Nom unique pour votre nouveau service Spring Boot
  labels:
    name: backend-service3    # Étiquette unique pour votre nouveau service Spring Boot
spec:
  type: NodePort
  ports:
    - port: 8040
      targetPort: 8040
      nodePort: 30009
  selector:
    app: backend-app3          # Étiquette unique pour votre nouveau déploiement Spring Boot