apiVersion: v1
kind: Service
metadata:
  name: springboot-backend4   # Nom unique pour votre nouveau service Spring Boot
  labels:
    name: backend-service4    # Étiquette unique pour votre nouveau service Spring Boot
spec:
  type: NodePort
  ports:
    - port: 8050
      targetPort: 8050
      nodePort: 30004
  selector:
    app: backend-app4       # Étiquette unique pour votre nouveau déploiement Spring Boot