apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend4-deploy        # Nom unique pour votre nouveau déploiement Spring Boot
  labels:
    app: backend-app4         # Étiquette unique pour votre nouveau déploiement Spring Boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app4   # Étiquette unique pour votre nouveau déploiement Spring Boot
  template:
    metadata:
      labels:
        app: backend-app4     # Étiquette unique pour votre nouveau déploiement Spring Boot
    spec:
      containers:
        - name: backend-container
          image: karma12/crud4-spring-boot  # Nouvelle image Docker pour votre application Spring Boot
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8050
          env:
            - name: DB_HOST
              value: mysqldb4       # Nom du service MySQL nouvellement créé
            - name: DB_NAME
              value: devops          # Nom unique pour votre nouvelle base de données MySQL
            - name: DB_USERNAME
              value: aycha
            - name: DB_PASSWORD
              value: root