apiVersion: v1
kind: Service
metadata:
  name: mysqldb3             # Nom unique pour votre nouveau service MySQL
  labels:
    name: mysql-service3     # Étiquette unique pour votre nouveau service MySQL
spec:
  ports:
    - port: 3307              # Changer le port du service MySQL (utilisez un port non utilisé)
      targetPort: 3306
  selector:
    app: mysqldb3         # Étiquette unique pour votre nouveau déploiement MySQL