apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql2-deploy  # Nom unique pour votre nouveau déploiement MySQL
  labels:
    app: mysqldb2      # Étiquette unique pour votre nouveau déploiement MySQL
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb2     # Étiquette unique pour votre nouveau déploiement MySQL
  template:
    metadata:
      labels:
        app: mysqldb2   # Étiquette unique pour votre nouveau déploiement MySQL
    spec:
      containers:
        - name: mysqldb
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: devops  # Nom unique pour votre nouvelle base de données MySQL